In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

In [3]:
url = "https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page=1"

In [4]:
page = requests.get(url)
page

In [5]:
soup = BeautifulSoup(page.text)

In [6]:
p = soup.find_all("div", class_ = "col-xs-12 col-sm-6 col-md-6 catlistinfo row-no-padding sec-slide-effect")
p

[<div class="col-xs-12 col-sm-6 col-md-6 catlistinfo row-no-padding sec-slide-effect">
 <div class="comparechk">
 <input class="brandCompareCheckbox" id="compare0" name="compareCheckbox" onclick="getBrandsForComparison()" type="checkbox" value="FIHL965662"/>
 <label for="compare0"><span></span></label>
 </div>
 <div class="padfb15">
 <a href="https://www.franchiseindia.com/brands/the-granios.43694" target="_blank">
 <div class="catimgmobile">
 <img alt="THE GRANIOS" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/the-granios_2.png"/>
 </div>
 </a>
 <div class="catlisthead">Quick Service Restaurants</div>
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/the-granios.43694" id="brandnamecategoryFIHL965662" target="_blank">
                 THE GRANIOS
             </a>
 </div>
 <span id="brandinvestmentFIHL965662" style="display: none;">
             INR  2 Lac  - 5 Lac
         </span>
 </div>
 <div class="catlistdest">
 <div class="catdleft pad20">
 <div class="cattxtimg trst">
 <div class="phoicon">
 <a data-target="#catgalleryform" data-toggle="modal">
 <i aria-hidden="true" class="fa fa-camera fa-2x" id="fran_FIHL965662" onclick="getImages(this.id)"></i>
 </a>
 </div>
 <img alt="THE GRANIOS" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/franchisor/template/slider/1105/1073541946.jpg"/>
 <div class="countpho">5 Store Photos</div>
 </div>
 <div class="subcat">
 <div>Locations looking for expansion</div>
                                             Delhi,
                                             Haryana,
                                             Himachal Pradesh,

                                             .... + 17 more
                                     </div>
 <div class="commanmbs">
 <div class="subcat">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="catbtn">
 <input id="FIHL965662" name="getFreeInfo" onclick="getfree()" type="checkbox"/>
 <label for="FIHL965662"><span></span></label>
 </div>
 <!--btn E-->
 </div>
 <!--mobile hide code start 1 -->
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/the-granios.43694" id="brandnamecategoryFIHL965662" target="_blank"><div class="catimg"><img alt="THE GRANIOS" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/the-granios_2.png"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  2 Lac  - 5 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 200 - 1300
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 10-20
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 khammam
             </div>
 </div>
 <!--mobile hide code  end 1 -->
 </div>
 <div class="catbottp">
 <div class="col-xs-12 col-sm-12 col-md-12">
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-thumbs-up fa-lg"></i>74 </div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-share-alt fa-lg"></i></div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-star-half-o fa-lg"></i>4.8</div>
 </div>
 </div>
 </div>,
 <div class="col-xs-12 col-sm-6 col-md-6 catlistinfo row-no-padding sec-slide-effect">
 <div class="comparechk">
 <input class="brandCompareCheckbox" id="compare1" name="compareCheckbox" onclick="getBrandsForComparison()" type="checkbox" value="FIHL403765"/>
 <label for="compare1"><span></span></label>
 </div>
 <div class="padfb15">
 <a href="https://www.franchiseindia.com/brands/what-a-sandwich.51513" target="_blank">
 <div class="catimgmobile">
 <img alt="What a Sandwich" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/what-a-sandwich_1.jpg"/>
 </div>
 </a>
 <div class="catlisthead">Quick Service Restaurants</div>
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/what-a-sandwich.51513" id="brandnamecategoryFIHL403765" target="_blank">
                 What a Sandwich
             </a>
 </div>
 <span id="brandinvestmentFIHL403765" style="display: none;">
             INR  50 K  - 2 Lac
         </span>
 </div>
 <div class="catlistdest">
 <div class="catdleft pad20">
 <div class="cattxtimg trst">
 <div class="phoicon">
 <a data-target="#catgalleryform" data-toggle="modal">
 <i aria-hidden="true" class="fa fa-camera fa-2x" id="fran_FIHL403765" onclick="getImages(this.id)"></i>
 </a>
 </div>
 <img alt="What a Sandwich" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/franchisor/template/slider/0905/1123/592430043.jpg"/>
 <div class="countpho">5 Store Photos</div>
 </div>
 <div class="subcat">
 <div>Locations looking for expansion</div>
                                             Delhi,
                                             Haryana,
                                             Himachal Pradesh,

                                             .... + 32 more
                                     </div>
 <div class="commanmbs">
 <div class="subcat">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="catbtn">
 <input id="FIHL403765" name="getFreeInfo" onclick="getfree()" type="checkbox"/>
 <label for="FIHL403765"><span></span></label>
 </div>
 <!--btn E-->
 </div>
 <!--mobile hide code start 1 -->
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/what-a-sandwich.51513" id="brandnamecategoryFIHL403765" target="_blank"><div class="catimg"><img alt="What a Sandwich" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/what-a-sandwich_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  50 K  - 2 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 200 - 250
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 100-200
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Pune
             </div>
 </div>
 <!--mobile hide code  end 1 -->
 </div>
 <div class="catbottp">
 <div class="col-xs-12 col-sm-12 col-md-12">
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-thumbs-up fa-lg"></i>48 </div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-share-alt fa-lg"></i></div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-star-half-o fa-lg"></i>4.6</div>
 </div>
 </div>
 </div>,
 <div class="col-xs-12 col-sm-6 col-md-6 catlistinfo row-no-padding sec-slide-effect">
 <div class="comparechk">
 <input class="brandCompareCheckbox" id="compare2" name="compareCheckbox" onclick="getBrandsForComparison()" type="checkbox" value="FIHL9252677"/>
 <label for="compare2"><span></span></label>
 </div>
 <div class="padfb15">
 <a href="https://www.franchiseindia.com/brands/Go69-Pizza.21117" target="_blank">
 <div class="catimgmobile">
 <img alt="Go69 Pizza" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/pizza.gif"/>
 </div>
 </a>
 <div class="catlisthead">Pizzeria</div>
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/Go69-Pizza.21117" id="brandnamecategoryFIHL9252677" target="_blank">
                 Go69 Pizza
             </a>
 </div>
 <span id="brandinvestmentFIHL9252677" style="display: none;">
             INR  5 Lac  - 10 Lac
         </span>
 </div>
 <div class="catlistdest">
 <div class="catdleft pad20">
 <div class="cattxtimg trst">
 <div class="phoicon">
 <a data-target="#catgalleryform" data-toggle="modal">
 <i aria-hidden="true" class="fa fa-camera fa-2x" id="fran_FIHL9252677" onclick="getImages(this.id)"></i>
 </a>
 </div>
 <img alt="Go69 Pizza" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/franchisor/template/slider/0122/2005065209.jpg"/>
 <div class="countpho">5 Store Photos</div>
 </div>
 <div class="subcat">
 <div>Locations looking for expansion</div>
                                             Delhi,
                                             Haryana,
                                             Himachal Pradesh,

                                             .... + 32 more
                                     </div>
 <div class="commanmbs">
 <div class="subcat">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="catbtn">
 <input id="FIHL9252677" name="getFreeInfo" onclick="getfree()" type="checkbox"/>
 <label for="FIHL9252677"><span></span></label>
 </div>
 <!--btn E-->
 </div>
 <!--mobile hide code start 1 -->
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/Go69-Pizza.21117" id="brandnamecategoryFIHL9252677" target="_blank"><div class="catimg"><img alt="Go69 Pizza" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/pizza.gif"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  5 Lac  - 10 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 800
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 50-100
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Lucknow
             </div>
 </div>
 <!--mobile hide code  end 1 -->
 </div>
 <div class="catbottp">
 <div class="col-xs-12 col-sm-12 col-md-12">
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-thumbs-up fa-lg"></i>166 </div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-share-alt fa-lg"></i></div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-star-half-o fa-lg"></i>4.5</div>
 </div>
 </div>
 </div>,
 <div class="col-xs-12 col-sm-6 col-md-6 catlistinfo row-no-padding sec-slide-effect">
 <div class="comparechk">
 <input class="brandCompareCheckbox" id="compare3" name="compareCheckbox" onclick="getBrandsForComparison()" type="checkbox" value="FIHL747566"/>
 <label for="compare3"><span></span></label>
 </div>
 <div class="padfb15">
 <a href="https://www.franchiseindia.com/brands/chicago-pizza.27821" target="_blank">
 <div class="catimgmobile">
 <img alt="CHICAGO PIZZA" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/chicago-pizza_1.jpg"/>
 </div>
 </a>
 <div class="catlisthead">Quick Service Restaurants</div>
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/chicago-pizza.27821" id="brandnamecategoryFIHL747566" target="_blank">
                 CHICAGO PIZZA
             </a>
 </div>
 <span id="brandinvestmentFIHL747566" style="display: none;">
             INR  10 Lac  - 20 Lac
         </span>
 </div>
 <div class="catlistdest">
 <div class="catdleft pad20">
 <div class="cattxtimg trst">
 <div class="phoicon">
 <a data-target="#catgalleryform" data-toggle="modal">
 <i aria-hidden="true" class="fa fa-camera fa-2x" id="fran_FIHL747566" onclick="getImages(this.id)"></i>
 </a>
 </div>
 <img alt="CHICAGO PIZZA" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/franchisor/template/slider/1205/1685982915.jpg"/>
 <div class="countpho">5 Store Photos</div>
 </div>
 <div class="subcat">
 <div>Locations looking for expansion</div>
                                             Delhi,
                                             Haryana,
                                             Himachal Pradesh,

                                             .... + 32 more
                                     </div>
 <div class="commanmbs">
 <div class="subcat">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="catbtn">
 <input id="FIHL747566" name="getFreeInfo" onclick="getfree()" type="checkbox"/>
 <label for="FIHL747566"><span></span></label>
 </div>
 <!--btn E-->
 </div>
 <!--mobile hide code start 1 -->
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/chicago-pizza.27821" id="brandnamecategoryFIHL747566" target="_blank"><div class="catimg"><img alt="CHICAGO PIZZA" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/chicago-pizza_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 150
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 100-200
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 New delhi
             </div>
 </div>
 <!--mobile hide code  end 1 -->
 </div>
 <div class="catbottp">
 <div class="col-xs-12 col-sm-12 col-md-12">
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-thumbs-up fa-lg"></i>269 </div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-share-alt fa-lg"></i></div>
 <div class="col-xs-4 col-sm-4 col-md-4 bd"><i aria-hidden="true" class="fa fa-star-half-o fa-lg"></i>4.7</div>
 </div>
 </div>
 </div>,
 <div class="col-xs-12 col-sm-6 col-md-6 catlistinfo row-no-padding sec-slide-effect">
 <div class="comparechk">
 <input class="brandCompareCheckbox" id="compare4" name="compareCheckbox" onclick="getBrandsForComparison()" type="checkbox" value="FIHL6269091"/>
 <label for="compare4"><span></span></label>
 </div>
 <div class="padfb15">
 <a href="https://www.franchiseindia.com/brands/brewbakes.20329" target="_blank">
 <div class="catimgmobile">
 <img alt="Brewbakes" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/brewbakes_2.jpg"/>
 </div>
 </a>
 <div class="catlisthead">Casual Dine Restaurants</div>
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/brewbakes.20329" id="brandnamecategoryFIHL6269091" target="_blank">
                 Brewbakes
             </a>
 </div>
 <span id="brandinvestmentFIHL6269091" style="display: none;">
             INR  30 Lac  - 50 Lac
         </span>
 </div>
 <div class="catlistdest">
 <div class="catdleft pad20">
 <div class="cattxtimg trst">
 <div class="phoicon">
 <a data-target="#catgalleryform" data-toggle="modal">
 <i aria-hidden="true" class="fa fa-camera fa-2x" id="fran_FIHL6269091" onclick="getImages(this.id)"></i>
 </a>
 </div>
 <img alt="Brewbakes" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/franchisor/template/slider/0109/0802/160665727.jpg"/>
 <div class="countpho">5 Store Photos</div>
 </div>
 <div class="subcat">
 <div>Locations looking for expansion</div>
                                             Delhi,
                                             Haryana,
                                             Himachal Pradesh,

                                             .... + 32 more
                                     </div>
 <div class="commanmbs">
 <div class="subcat">
 <span>Establishment year</span>
                     2014
                 </div>
 <div class="subcat">
 <span>Franchising Launch Date</span>
                     2015
                 </div>
 </div>
 <!--mobile code 2 start here -->
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2014
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2015
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     500 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>

In [7]:
q = soup.find_all("div", class_ = "catlist")
q

[<div class="catlist">
 <a href="https://www.franchiseindia.com/brands/the-granios.43694" id="brandnamecategoryFIHL965662" target="_blank">
                 THE GRANIOS
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/what-a-sandwich.51513" id="brandnamecategoryFIHL403765" target="_blank">
                 What a Sandwich
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/Go69-Pizza.21117" id="brandnamecategoryFIHL9252677" target="_blank">
                 Go69 Pizza
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/chicago-pizza.27821" id="brandnamecategoryFIHL747566" target="_blank">
                 CHICAGO PIZZA
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/brewbakes.20329" id="brandnamecategoryFIHL6269091" target="_blank">
                 Brewbakes
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/Us-Pizza.27020" id="brandnamecategoryFIHL3351612" target="_blank">
                 U.S. Pizza
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/stark-bistro.23941" id="brandnamecategoryFIHL783634" target="_blank">
                 Stark Bistro
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/Frespresso.20265" id="brandnamecategoryFIHL460691" target="_blank">
                 Frespresso Hospitality Pvt Ltd
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/sandwich-junction.43464" id="brandnamecategoryFIHL497487" target="_blank">
                 Sandwich Junction
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/american-burger-cafe.73736" id="brandnamecategoryFIHL717244" target="_blank">
                 American Burger cafe
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/regional-foods.65540" id="brandnamecategoryFIHL527416" target="_blank">
                 Regional Foods
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/karims.30726" id="brandnamecategoryFIHL561682" target="_blank">
                 Karim’s
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/kathi-express.27144" id="brandnamecategoryFIHL4278392" target="_blank">
                 Kathi Express
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/round-slice.67082" id="brandnamecategoryFIHL517196" target="_blank">
                 Round Slice
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/michaels-icecream-burger.32262" id="brandnamecategoryFIHL194987" target="_blank">
                 Michaels Icecream Burger
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/jo-paji-foods.75534" id="brandnamecategoryFIHL783339" target="_blank">
                 AGS MEGA MART LLP
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/scuzo.67848" id="brandnamecategoryFIHL840875" target="_blank">
                 Scuzo
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/punnu-biriyani.72967" id="brandnamecategoryFIHL108206" target="_blank">
                 Punnu Biriyani
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/figaros-pizza.73238" id="brandnamecategoryFIHL557776" target="_blank">
                 Figaro's Italian Pizza
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/franky-station.73742" id="brandnamecategoryFIHL438468" target="_blank">
                 Franky Station
             </a>
 </div>,
 <div class="catlist">
 <a href="https://www.franchiseindia.com/brands/bts-coffee-india.69897" id="brandnamecategoryFIHL884103" target="_blank">
                 BTS Coffee India
             </a>
 </div>]

In [8]:
data = soup.find_all("div", class_ = "subcat pleft")
data

[<div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2014
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>,
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>,
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>,
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>]

In [9]:
data1=soup.find_all("div" , class_ = "commanmbsmobile")#[0].text.replace("\n","").split()[2]
data1

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2014
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2015
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     500 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [10]:
data2=soup.find_all("div" , class_ = "commanmbsmobile")#[0].text.replace("\n","")
data2

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2014
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2015
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     500 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [10]:
Establishment = []
for i in data1:
    a = i.text
    Establishment.append(a.replace("\n","").split()[2])
Establishment

['2013',
 '2013',
 '2015',
 '2000',
 '1998',
 '2001',
 '2016',
 '2010',
 '2012',
 '2021',
 '1980',
 '2003',
 '2019',
 '1950',
 '2020',
 '2017',
 '2018',
 '1981',
 '2021',
 '2017',
 '2021']

In [11]:
Company = []
for i in q:
    a = i.text
    b=a.strip()
    Company.append(b.replace("\n",""))
    #c = append(b)
Company

['What a Sandwich',
 'THE GRANIOS',
 'Go69 Pizza',
 'CHICAGO PIZZA',
 'U.S. Pizza',
 'KK Thali by Hotel KK',
 'Stark Bistro',
 'Frespresso Hospitality Pvt Ltd',
 'Sandwich Junction',
 'AGS MEGA MART LLP',
 'Punnu Biriyani',
 'Kathi Express',
 'Round Slice',
 'Karim’s',
 'Scuzo',
 'Franky Station',
 'Regional Foods',
 "Figaro's Italian Pizza",
 'BTS Coffee India',
 'Michaels Icecream Burger',
 'American Burger cafe']

In [12]:
a.replace("\n","")

'                American Burger cafe            '

In [13]:
data2=soup.find_all("div" , class_ = "commanmbsmobile")#[0].text.split("INR")[1].split('\n')[0]
data2

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2001
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1000 - 3500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [14]:
Investment = []
for i in data2:
    a = i.text
    b = Investment.append(a.split("INR")[1].split('\n')[0])
Investment

['  50 K  - 2 Lac ',
 '  2 Lac  - 5 Lac ',
 '  5 Lac  - 10 Lac ',
 '  10 Lac  - 20 Lac ',
 '  20 Lac  - 30 Lac ',
 '  20 Lac  - 30 Lac ',
 '  5 Lac  - 10 Lac ',
 '  10 Lac  - 20 Lac ',
 '  10 Lac  - 2 Cr ',
 '  10 Lac  - 20 Lac ',
 '  10 Lac  - 20 Lac ',
 '  2 Lac  - 5 Lac ',
 '  50 Lac  - 1 Cr ',
 '  50 Lac  - 1 Cr ',
 '  10 Lac  - 20 Lac ',
 '  10 Lac  - 20 Lac ',
 '  1 Cr  - 2 Cr ',
 '  30 Lac  - 50 Lac ',
 '  10 Lac  - 20 Lac ',
 '  5 Lac  - 10 Lac ',
 '  10 Lac  - 20 Lac ']

In [15]:
Min_Invest= []
for i in data2:
    a = i.text
    b = Min_Invest.append(a.split("INR")[1].split('\n')[0].split('-')[0])
Min_Invest

['  50 K  ',
 '  2 Lac  ',
 '  5 Lac  ',
 '  10 Lac  ',
 '  20 Lac  ',
 '  20 Lac  ',
 '  5 Lac  ',
 '  10 Lac  ',
 '  10 Lac  ',
 '  10 Lac  ',
 '  10 Lac  ',
 '  2 Lac  ',
 '  50 Lac  ',
 '  50 Lac  ',
 '  10 Lac  ',
 '  10 Lac  ',
 '  1 Cr  ',
 '  30 Lac  ',
 '  10 Lac  ',
 '  5 Lac  ',
 '  10 Lac  ']

In [16]:
Max_Invest= []
for i in data2:
    a = i.text
    b = Max_Invest.append(a.split("INR")[1].split('\n')[0].split('-')[1])
Max_Invest

[' 2 Lac ',
 ' 5 Lac ',
 ' 10 Lac ',
 ' 20 Lac ',
 ' 30 Lac ',
 ' 30 Lac ',
 ' 10 Lac ',
 ' 20 Lac ',
 ' 2 Cr ',
 ' 20 Lac ',
 ' 20 Lac ',
 ' 5 Lac ',
 ' 1 Cr ',
 ' 1 Cr ',
 ' 20 Lac ',
 ' 20 Lac ',
 ' 2 Cr ',
 ' 50 Lac ',
 ' 20 Lac ',
 ' 10 Lac ',
 ' 20 Lac ']

In [17]:
data2=soup.find_all("div" , class_ = "commanmbsmobile")#[0].text.split("Date")[1].split()[0]
data2

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2001
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1000 - 3500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [18]:
Launching = []
for i in data2:
    a = i.text
    b = Launching.append(a.split("Date")[1].split()[0])
Launching

['2018',
 '2017',
 '2016',
 '2007',
 '2002',
 '2022',
 '2016',
 '2010',
 '2018',
 '2022',
 '2022',
 '2003',
 '2020',
 '2018',
 '2020',
 '2022',
 '2020',
 '2001',
 '2021',
 '2019',
 '2022']

In [19]:
data2=soup.find_all("div" , class_ = "commanmbsmobile")#[0].text.split('required')[1].split('\n')[1].split()[0]
data2

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2001
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1000 - 3500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [20]:
space = []
for i in data2:
    a = i.text
    b = space.append(a.split('required')[1].split('\n')[1].strip())
space

['200 - 250',
 '200 - 1300',
 '100 - 800',
 '100 - 150',
 '250 - 1000',
 '1000 - 3500',
 '100 - 5000',
 '100 - 1000',
 '100 - 1000',
 '300 - 2000',
 '200 - 400',
 '100 - 400',
 '800 - 1000',
 '250 - 2000',
 '100 - 300',
 '250 - 400',
 '1200 - 1500',
 '-N/A-',
 '00 - 000',
 '100 - 500',
 '150 - 300']

In [21]:
minspace = []
for i in data2:
    a = i.text
    minspace.append(a.split('required')[1].split('\n')[1].split()[0])
minspace

['200',
 '200',
 '100',
 '100',
 '250',
 '1000',
 '100',
 '100',
 '100',
 '300',
 '200',
 '100',
 '800',
 '250',
 '100',
 '250',
 '1200',
 '-N/A-',
 '00',
 '100',
 '150']

In [22]:
data2=soup.find_all("div" , class_ = "commanmbsmobile")#[0].text.split('required')[1].split('\n')[1].split()[2]
data2

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2001
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1000 - 3500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [23]:
maxspace = []
for i in data2:
    a = i.text
    maxspace.append(a.split('required')[1].split('\n')[1].split())
maxspace

[['200', '-', '250'],
 ['200', '-', '1300'],
 ['100', '-', '800'],
 ['100', '-', '150'],
 ['250', '-', '1000'],
 ['1000', '-', '3500'],
 ['100', '-', '5000'],
 ['100', '-', '1000'],
 ['100', '-', '1000'],
 ['300', '-', '2000'],
 ['200', '-', '400'],
 ['100', '-', '400'],
 ['800', '-', '1000'],
 ['250', '-', '2000'],
 ['100', '-', '300'],
 ['250', '-', '400'],
 ['1200', '-', '1500'],
 ['-N/A-'],
 ['00', '-', '000'],
 ['100', '-', '500'],
 ['150', '-', '300']]

In [24]:
data3=soup.find_all("div",class_="commanmbsmobile")#[0].text.split('Franchise Outlets')[0]
data3

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2001
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1000 - 3500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [25]:
ftype = []
for i in data3:
    a = i.text
    ftype.append(a.split('Franchise')[1].split('\n')[1].strip())
ftype

['Unit, Multiunit',
 'Unit',
 'Unit',
 'Unit, Multiunit',
 'Unit',
 'Unit',
 'Unit, Multiunit',
 'Unit, Multiunit',
 'Unit, Multiunit',
 'Unit, Multiunit',
 'Unit',
 'Unit',
 'Unit',
 'Unit',
 'Unit',
 'Unit',
 'Unit',
 'Unit',
 'Unit',
 'Unit, Multiunit',
 'Unit']

In [26]:
data4 = soup.find_all("div" , class_ = "subcat")[0].text.split()
data4

['Locations',
 'looking',
 'for',
 'expansion',
 'Delhi,',
 'Haryana,',
 'Himachal',
 'Pradesh,',
 '....',
 '+',
 '32',
 'more']

In [27]:
data2=soup.find_all("div" , class_ = "commanmbsmobile")#[4].text.split('Franchise')[2].split('\n')[1].strip()
data2

[<div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 K  - 2 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 250
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2013
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2017
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 1300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2015
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 800
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2000
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2007
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 150
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     100-200
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1998
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2002
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     50-100
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2001
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  20 Lac  - 30 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1000 - 3500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2016
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2016
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 5000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     10-20
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2010
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2010
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2012
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     300 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1980
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     200 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2003
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2003
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  2 Lac  - 5 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2019
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     800 - 1000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1950
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2018
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  50 Lac  - 1 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 2000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2020
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     250 - 400
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2018
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2020
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  1 Cr  - 2 Cr
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     1200 - 1500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     1981
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2001
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  30 Lac  - 50 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     -N/A-
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     200-500
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2021
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     00 - 000
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2017
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2019
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  5 Lac  - 10 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     100 - 500
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit, Multiunit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     20-50
                 </div>
 </div>,
 <div class="commanmbsmobile">
 <div class="subcat pleft">
 <span>Establishment year</span>
                     2021
                 </div>
 <div class="subcat pright">
 <span>Franchising Launch Date</span>
                     2022
                 </div>
 <div class="subcat pleft">
 <span>Investment size</span>
                     INR  10 Lac  - 20 Lac
                 </div>
 <div class="subcat pright"><span>Space required</span>
                     150 - 300
                 </div>
 <div class="subcat pleft">
 <span>Franchise Type</span>
                         Unit
                     </div>
 <div class="subcat pright">
 <span>Franchise Outlets</span>
                     Less than 10
                 </div>
 </div>]

In [28]:
outlets = []
for i in data2:
    a = i.text
    outlets.append(a.split('Franchise')[2].split('\n')[1].strip())
outlets

['100-200',
 '10-20',
 '50-100',
 '100-200',
 '50-100',
 'Less than 10',
 '10-20',
 '20-50',
 '20-50',
 'Less than 10',
 'Less than 10',
 '20-50',
 'Less than 10',
 '20-50',
 'Less than 10',
 'Less than 10',
 'Less than 10',
 '200-500',
 'Less than 10',
 '20-50',
 'Less than 10']

In [29]:
r = soup.find_all('div', class_ = "catdright pad20")#[0].text.split('Headquarter')[1].split('\n')[1].strip()
r

[<div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/what-a-sandwich.51513" id="brandnamecategoryFIHL403765" target="_blank"><div class="catimg"><img alt="What a Sandwich" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/what-a-sandwich_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  50 K  - 2 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 200 - 250
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 100-200
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Pune
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/the-granios.43694" id="brandnamecategoryFIHL965662" target="_blank"><div class="catimg"><img alt="THE GRANIOS" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/the-granios_2.png"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  2 Lac  - 5 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 200 - 1300
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 10-20
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 khammam
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/Go69-Pizza.21117" id="brandnamecategoryFIHL9252677" target="_blank"><div class="catimg"><img alt="Go69 Pizza" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/pizza.gif"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  5 Lac  - 10 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 800
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 50-100
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Lucknow
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/chicago-pizza.27821" id="brandnamecategoryFIHL747566" target="_blank"><div class="catimg"><img alt="CHICAGO PIZZA" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/chicago-pizza_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 150
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 100-200
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 New delhi
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/Us-Pizza.27020" id="brandnamecategoryFIHL3351612" target="_blank"><div class="catimg"><img alt="U.S. Pizza" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/Us-Pizza_4.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  20 Lac  - 30 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 250 - 1000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 50-100
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Bangalore Urban District
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/kk-thali.73440" id="brandnamecategoryFIHL430174" target="_blank"><div class="catimg"><img alt="KK Thali by Hotel KK" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/kk-thali_3.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  20 Lac  - 30 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 1000 - 3500
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Rajkot
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/stark-bistro.23941" id="brandnamecategoryFIHL783634" target="_blank"><div class="catimg"><img alt="Stark Bistro" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/stark-bistro_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  5 Lac  - 10 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 5000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 10-20
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Bhubaneswar
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/Frespresso.20265" id="brandnamecategoryFIHL460691" target="_blank"><div class="catimg"><img alt="Frespresso Hospitality Pvt Ltd" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/Frespresso_1.gif"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 1000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 20-50
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 vapi
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/sandwich-junction.43464" id="brandnamecategoryFIHL497487" target="_blank"><div class="catimg"><img alt="Sandwich Junction" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/sandwich-junction_1.gif"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 2 Cr
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 1000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 20-50
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Pune
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/jo-paji-foods.75534" id="brandnamecategoryFIHL783339" target="_blank"><div class="catimg"><img alt="AGS MEGA MART LLP" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/jo-paji-foods_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 300 - 2000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Ghaziabad
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/punnu-biriyani.72967" id="brandnamecategoryFIHL108206" target="_blank"><div class="catimg"><img alt="Punnu Biriyani" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/punnu-biriyani_2.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 200 - 400
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 New delhi
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/kathi-express.27144" id="brandnamecategoryFIHL4278392" target="_blank"><div class="catimg"><img alt="Kathi Express" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/kathi-express_3.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  2 Lac  - 5 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 400
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 20-50
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Dehradun
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/round-slice.67082" id="brandnamecategoryFIHL517196" target="_blank"><div class="catimg"><img alt="Round Slice" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/round-slice_1.png"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  50 Lac  - 1 Cr
             </div>
 <div class="subcat"><span>Space required</span>
                 800 - 1000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Ahmedabad
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/karims.30726" id="brandnamecategoryFIHL561682" target="_blank"><div class="catimg"><img alt="Karim’s" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/karims_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  50 Lac  - 1 Cr
             </div>
 <div class="subcat"><span>Space required</span>
                 250 - 2000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 20-50
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 New delhi
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/scuzo.67848" id="brandnamecategoryFIHL840875" target="_blank"><div class="catimg"><img alt="Scuzo" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/scuzo_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 300
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 New delhi
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/franky-station.73742" id="brandnamecategoryFIHL438468" target="_blank"><div class="catimg"><img alt="Franky Station" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/franky-station_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 250 - 400
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Vadodara
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/regional-foods.65540" id="brandnamecategoryFIHL527416" target="_blank"><div class="catimg"><img alt="Regional Foods" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/regional-foods_3.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  1 Cr  - 2 Cr
             </div>
 <div class="subcat"><span>Space required</span>
                 1200 - 1500
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Thane
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/figaros-pizza.73238" id="brandnamecategoryFIHL557776" target="_blank"><div class="catimg"><img alt="Figaro's Italian Pizza" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/figaros-pizza_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  30 Lac  - 50 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 -N/A-
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 200-500
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Faridabad
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/bts-coffee-india.69897" id="brandnamecategoryFIHL884103" target="_blank"><div class="catimg"><img alt="BTS Coffee India" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/bts-coffee-india_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 00 - 000
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Noida
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/michaels-icecream-burger.32262" id="brandnamecategoryFIHL194987" target="_blank"><div class="catimg"><img alt="Michaels Icecream Burger" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/michaels-icecream-burger_3.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  5 Lac  - 10 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 100 - 500
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 20-50
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit, Multiunit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Bangalore
             </div>
 </div>,
 <div class="catdright pad20">
 <a href="https://www.franchiseindia.com/brands/american-burger-cafe.73736" id="brandnamecategoryFIHL717244" target="_blank"><div class="catimg"><img alt="American Burger cafe" src="https://franchiseindia.s3.ap-south-1.amazonaws.com/uploads/franchisor/american-burger-cafe_1.jpg"/></div></a>
 <div class="subcat"><span>Investment size</span>
                 INR  10 Lac  - 20 Lac
             </div>
 <div class="subcat"><span>Space required</span>
                 150 - 300
             </div>
 <div class="subcat">
 <span>Franchise Outlets</span>
                 Less than 10
             </div>
 <div class="subcat"><span>Franchise Type</span>                                        Unit
                 </div>
 <div class="subcat">
 <span>Headquarter</span>
                 Delhi
             </div>
 </div>]

In [30]:
hq = []
for i in r:
    a = i.text
    hq.append(a.split('Headquarter')[1].split('\n')[1].strip())
hq

['Pune',
 'khammam',
 'Lucknow',
 'New delhi',
 'Bangalore Urban District',
 'Rajkot',
 'Bhubaneswar',
 'vapi',
 'Pune',
 'Ghaziabad',
 'New delhi',
 'Dehradun',
 'Ahmedabad',
 'New delhi',
 'New delhi',
 'Vadodara',
 'Thane',
 'Faridabad',
 'Noida',
 'Bangalore',
 'Delhi']

In [31]:
len(hq)

21

# DataFrame

#### *Food and Bevarages*

In [11]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space[]
hq = []


for i in range(1,7):
    url = "https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
        
    for i in data2:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])
    
    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())
           
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Franchise')[2].split('\n')[1].strip())    

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page=4
https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page=5
https://www.franchiseindia.com/business-opportunities/food-and-beverage.m2?sortby=&page=6

In [12]:
b = {"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [34]:
print(len(Company))
print(len(Establishment))
print(len(Launching))
print(len(Min_Invest))
print(len(Max_Invest))
print(len(outlets))
print(len(minspace))
print(len(maxspace))
print(len(hq))

126
126
126
126
126
126
126
126
126

In [13]:
bf = pd.DataFrame(b)
bf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,What a Sandwich,2013,2018,2 Lac - 5 Lac,200 - 1300,100-200,Pune
1,Go69 Pizza,2015,2016,50 K - 2 Lac,200 - 250,50-100,Lucknow
2,THE GRANIOS,2013,2017,5 Lac - 10 Lac,100 - 800,10-20,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac - 20 Lac,100 - 150,100-200,New delhi
4,Brewbakes,2014,2015,30 Lac - 50 Lac,500 - 2000,100-200,Delhi
...,...,...,...,...,...,...,...
121,Candle Light Date N Dinner Restaurant,2014,2022,10 Lac - 20 Lac,100 - 300,Less than 10,Ahmedabad
122,La Pizza Parkway Cafe,2020,2022,10 Lac - 20 Lac,200 - 400,Less than 10,Pardi
123,KUDRATI KAHUMBO,2000,2022,30 Lac - 50 Lac,-N/A-,20-50,Ahmedabad
124,Apna Fal & ShakeSee,2019,2022,10 Lac - 20 Lac,250 - 400,Less than 10,Ahmedabad
125,Cafe Choco Craze Pvt Ltd,2010,2012,10 Lac - 20 Lac,00 - 000,50-100,Haveli

In [36]:
bf.describe(include = 'all')

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
count,126,126,126,126,126,126,126,126,126
unique,126,37,20,10,10,6,27,35,56
top,What a Sandwich,2020,2022,10 Lac,20 Lac,Less than 10,100,500,Ahmedabad
freq,1,17,65,47,46,85,21,13,21

In [37]:
bf.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lac,100-200,200,250,Pune
1,Go69 Pizza,2015,2016,5 Lac,10 Lac,50-100,100,800,Lucknow
2,THE GRANIOS,2013,2017,2 Lac,5 Lac,10-20,200,1300,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac,20 Lac,100-200,100,150,New delhi
4,U.S. Pizza,1998,2002,20 Lac,30 Lac,50-100,250,1000,Bangalore Urban District

In [38]:
bf['Outlets'].value_counts()

Less than 10    85
100-200         15
20-50           10
10-20            8
50-100           6
200-500          2
Name: Outlets, dtype: int64

In [39]:
bf['Launching Year'].value_counts()

2022    65
2020    17
2021    11
2018     6
2019     5
2017     4
2014     2
2009     2
2016     2
2001     2
2003     1
2010     1
2004     1
2000     1
2015     1
2002     1
2007     1
2012     1
2005     1
1991     1
Name: Launching Year, dtype: int64

### *Automotive*

In [60]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []


for i in range(1,20):
    url = "https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
           
    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])
    
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())    

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=4
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=5
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=6
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=7
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=8
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=9
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=10
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=11
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=12
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=13
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=14
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=15
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=16
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=17
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=18
https://www.franchiseindia.com/business-opportunities/automotive.m8?sortby=&page=19

In [61]:
e ={"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [42]:
print(len(Company))
print(len(Establishment))
print(len(Launching))
print(len(Min_Invest))
print(len(Max_Invest))
print(len(outlets))
print(len(minspace))
print(len(maxspace))
print(len(hq))

42
42
42
42
42
42
42
42
42

In [62]:
ef = pd.DataFrame(e)
ef

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,ZEON charging,2019,2020,10 Lac - 20 Lac,150 - 150,Less than 10,Avanashi
1,FILMSHOPPEE,2006,2022,30 Lac - 50 Lac,1300 - 1300,Less than 10,Surat
2,Servizzy,2020,2022,10 Lac - 20 Lac,1800 - 2000,Less than 10,Gurgaon
3,Tirex,2017,2020,10 Lac - 20 Lac,300 - 300,100-200,Bavla
4,ONYXAA,2016,2020,30 Lac - 50 Lac,2000 - 4000,Less than 10,Delhi
5,Credr,2015,2020,30 Lac - 50 Lac,1200 - 2000,Less than 10,Bangalore
6,Permagard,1998,2022,30 Lac - 50 Lac,1500 - 2000,10-20,Ahmedabad
7,Chargepod,2022,2022,10000 - 50 K,4000 - 10000,Less than 10,Daskroi
8,Bharat Cycles,2011,2021,20 Lac - 30 Lac,500 - 750,Less than 10,Bassein
9,Eco Rent a Car,1974,2015,30 Lac - 50 Lac,00 - 000,Less than 10,New delhi
10,Bounce Infinity – Battery Swapping Infra,2018,2018,2 Lac - 5 Lac,10 - 015,Less than 10,Bengaluru
11,Speed Force,2013,2017,5 Lac - 10 Lac,500 - 1000,200-500,Vadodara
12,Serviceforce,2011,2013,5 Lac - 20 Lac,400 - 600,200-500,Rajkot
13,Bounce Infinity - Auto Dealership,2021,2022,50 Lac - 1 Cr,500 - 1500,Less than 10,Bangalore
14,Blive,2021,2021,5 Lac - 10 Lac,500 - 500,Less than 10,Tiswaddi
15,eBikeGo Private Limited,2019,2023,50 Lac - 1 Cr,300 - 300,Less than 10,Mumbai
16,Zuink Retrofit,2021,2021,5 Lac - 10 Lac,350 - 400,Less than 10,Bangalore
17,ECO RAC,1996,2020,20 Lac - 30 Lac,200 - 200,50-100,New delhi
18,Envo Sustainer Pvt Ltd,2019,2021,1 Cr - 2 Cr,100 - 1000,Less than 10,Thane
19,Gulf Oil Lubricants India Ltd,2011,2011,0 - 0,150 - 300,100-200,Gurugram
20,5K CAR CARE PVT LTD,2012,2018,30 Lac - 50 Lac,800 - 4000,50-100,Coimbatore
21,CEAT,1950,1958,10 Lac - 20 Lac,500 - 1200,50-100,Mumbai
22,Ajmera Tyres Pvt. Ltd.,1968,2019,20 Lac - 30 Lac,1000 - 1500,Less than 10,Nagpur
23,Castrol Auto Service,2021,2021,5 Lac - 10 Lac,3000 - 5000,20-50,Mumbai
24,FAE Bikes,2016,2020,30 Lac - 50 Lac,10 - 100,Less than 10,Bangalore
25,CARZSPA INDIA,2006,2006,5 Lac - 10 Lac,400 - 600,Less than 10,Surat
26,AUTO HERB,2014,2015,10 Lac - 30 Lac,1000 - 2000,20-50,Pune
27,Delta Autocorp LLP,2016,2017,10000 - 50 K,800 - 1500 Sq.ft,20-50,Kolkata
28,Mahindra First Choice Services Ltd.,2007,2014,50 Lac - 1 Cr,5000 - 10000,200-500,Mumbai
29,ChangeMyTyre,2012,2013,10000 - 50 K,1000-1500 sq ft,Less than 10,Gurgaon
30,Grand Prix Car Detailing PVT LTD,2017,2018,5 Lac - 10 Lac,500 - 1500,Less than 10,NaviMumbai
31,TARGETONE INNOVATIONS PVT LTD (Go Mechanic),2016,2019,10 Lac - 1 Cr,250 - 1000,10-20,Gurgaon
32,VA-YU,2020,2021,20 Lac - 30 Lac,000 - 000,Less than 10,New delhi
33,Go Waterless,2019,2019,2 Lac - 5 Lac,-N/A-,50-100,Pune
34,M2Go Electric Vehicle Pvt Ltd,2019,2019,30 Lac - 50 Lac,1000 - 1500,Less than 10,New delhi
35,FIXIGO,2020,2020,5 Lac - 10 Lac,00 - 000,Less than 10,New delhi
36,VALUE ADDED TYRE SOLUTIONS PVT. LTD,2011,2020,50 Lac - 1 Cr,2500 - 10000,Less than 10,Aluva
37,Adrol,1968,2020,20 Lac - 30 Lac,700 - 1000,Less than 10,New delhi
38,Statiq,2020,2020,10 Lac - 20 Lac,150 - 150,Less than 10,gurgaon
39,EFILL,2019,2021,10 Lac - 20 Lac,150 - 150,Less than 10,Sonipat
40,Vihan Electric Vehicles Company,2015,2015,5 Lac - 10 Lac,500 - 2000 Sq.ft,Less than 10,Pune
41,Luxury Ride,2015,2018,2 Cr - 5 Cr,12000 - 18000,Less than 10,Delhi
42,Freego Bikes Pvt Ltd,2014,2018,0 - 0,250 - 500,No,Jogeshwari east

In [ ]:
ef.describe(include = 'all')

In [45]:
ef.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,Bounce Infinity – Battery Swapping Infra,2018,2018,2 Lac,5 Lac,Less than 10,10,015,Bengaluru
1,Zuink Retrofit,2021,2021,5 Lac,10 Lac,Less than 10,350,400,Bangalore
2,Servizzy,2020,2022,10 Lac,20 Lac,Less than 10,1800,2000,Gurgaon
3,FILMSHOPPEE,2006,2022,30 Lac,50 Lac,Less than 10,1300,1300,Surat
4,Permagard,1998,2022,30 Lac,50 Lac,10-20,1500,2000,Ahmedabad

### *Beauty and Health*

In [64]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []


for i in range(1,20):
    url = "https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
        
    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])
    
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=4
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=5
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=6
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=7
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=8
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=9
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=10
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=11
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=12
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=13
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=14
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=15
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=16
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=17
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=18
https://www.franchiseindia.com/business-opportunities/beauty-and-health.m1?sortby=&page=19

In [65]:
f = {"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [48]:
print(len(Company))
print(len(Establishment))
print(len(Launching))
print(len(Min_Invest))
print(len(Max_Invest))
print(len(outlets))
print(len(minspace))
print(len(maxspace))
print(len(hq))

90
90
90
90
90
90
90
90
90

In [66]:
ff = pd.DataFrame(f)
ff

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,Studio99 Salons,2017,2018,30 Lac - 50 Lac,800 - 3000,20-50,Delhi
1,JAWED HABIB HAIR AND BEAUTY LIMITED,2006,2009,30 Lac - 50 Lac,500 - 1500,500-1000,Mumbai
2,JUICE,2000,2003,30 Lac - 50 Lac,1200 - 2500,20-50,Mumbai
3,The Man Company,2015,2020,10 Lac - 20 Lac,50 - 200,10-20,Gurugram
4,Jean Claude Olivier India,2019,2022,50 Lac - 1 Cr,1500 - 2000,Less than 10,Mumbai
...,...,...,...,...,...,...,...
86,Medlife Pharma healthcare Pvt Ltd,2014,2017,50 K - 2 Lac,120 - 200,Less than 10,Chalisgaon
87,Framekart.com,1995,2019,10000 - 50 K,200 - 3000,Less than 10,Patna
88,"Max Lab, A Division of Max Healthcare Institut...",2016,2016,50 K - 2 Lac,150 - 200,100-200,Gurgaon
89,NephroPlus,2009,2020,10 Lac - 20 Lac,1330 - 1330,Less than 10,Faridabad
90,Ayouthveda,2020,2021,30 Lac - 50 Lac,300 - 400,Less than 10,Delhi

In [67]:
ff.describe(include = 'all')

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
count,91,91,91,91,91,91,91
unique,91,28,19,11,64,12,43
top,Studio99 Salons,2017,2022,10 Lac - 20 Lac,-N/A-,Less than 10,Faridabad
freq,1,9,29,26,9,54,10

In [95]:
ff.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,JAWED HABIB HAIR AND BEAUTY LIMITED,2006,2009,30 Lac,50 Lac,500-1000,500,"[500, -, 1500]",Mumbai
1,JUICE,2000,2003,30 Lac,50 Lac,20-50,1200,"[1200, -, 2500]",Mumbai
2,Ozone Yoga,2017,2022,10 Lac,20 Lac,Less than 10,1500,"[1500, -, 2000]",Ahmedangar
3,PharmEasy,1995,2022,50 K,2 Lac,20-50,150,"[150, -, 250]",Faridabad
4,Beardo,2015,2015,5 Lac,10 Lac,Less than 10,80,"[80, -, 100]",Ahmedabad

### *Sports, Fitness and Entertainment*

In [55]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []


for i in range(1,20):
    url = "https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
           
    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])
    
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())    
        

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=4
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=5
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=6
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=7
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=8
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=9
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=10
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=11
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=12
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=13
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=14
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=15
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=16
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=17
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=18
https://www.franchiseindia.com/business-opportunities/sports-fitness-and-entertainment.m11?sortby=&page=19

In [56]:
g = {"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [54]:
print(len(Company))
print(len(Establishment))
print(len(Launching))
print(len(Min_Invest))
print(len(Max_Invest))
print(len(outlets))
print(len(minspace))
print(len(maxspace))
print(len(hq))

14
14
14
14
14
14
14
14
14

In [57]:
gf = pd.DataFrame(g)
gf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,Dazzle SportsWear,2006,2020,20 Lac - 30 Lac,500 - 500,Less than 10,telangna
1,Alcis,2018,2018,20 Lac - 30 Lac,500 - 1000,Less than 10,Dadri
2,Your Fitness,2021,2021,50 Lac - 1 Cr,3000 - 5000,Less than 10,Mumbai
3,Sporty Beans,2009,2022,5 Lac - 10 Lac,1500 - 1500,50-100,Pune
4,ACME Fitness,1998,2022,30 Lac - 50 Lac,750 - 1000,20-50,New delhi
5,Funplex Game zone,2016,2022,2 Cr - 5 Cr,6000 - 10000,Less than 10,Indore
6,Swing & Spin,2019,2022,10 Lac - 20 Lac,1000 - 1200,Less than 10,Gurgaon
7,New Fangled,2019,2022,1 Cr - 2 Cr,5000 - 5000,Less than 10,Ahmedabad
8,THE CONNPLEX SMART THEATRE,2009,2019,50 Lac - 1 Cr,5000 - 8000,100-200,Delhi
9,Eos Cinemas Pvt. Ltd,2013,2015,50 Lac - 1 Cr,-N/A-,Less than 10,Bastar
10,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lac - 1 Cr,2000 - 4000,Less than 10,Deharaudn
11,ResQRoom,2016,2018,10 Lac - 20 Lac,700 - 900,10-20,Haveli
12,House of Fitness pvt ltd,2012,2012,2 Cr - 5 Cr,3500 - 5000,50-100,Delhi
13,All Things love,2016,2020,10 Lac - 20 Lac,500 - 5000,Less than 10,Gurgaon

In [56]:
gf.describe(include = 'all')

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
count,14,14,14,14,14,14,14,14,14
unique,14,10,7,7,7,5,11,14,12
top,Swing & Spin,2016,2022,50 Lac,1 Cr,Less than 10,500,1000 - 1200,Gurgaon
freq,1,3,5,4,4,9,3,1,2

In [57]:
gf.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,Swing & Spin,2019,2022,10 Lac,20 Lac,Less than 10,1000,1000 - 1200,Gurgaon
1,Sporty Beans,2009,2022,5 Lac,10 Lac,50-100,1500,1500 - 1500,Pune
2,Alcis,2018,2018,20 Lac,30 Lac,Less than 10,500,500 - 1000,Dadri
3,Funplex Game zone,2016,2022,2 Cr,5 Cr,Less than 10,6000,6000 - 10000,Indore
4,New Fangled,2019,2022,1 Cr,2 Cr,Less than 10,5000,5000 - 5000,Ahmedabad

### *Education*

In [47]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []


for i in range(1,20):
    url = "https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
           
    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])

    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())    
        

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=4
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=5
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=6
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=7
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=8
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=9
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=10
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=11
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=12
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=13
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=14
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=15
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=16
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=17
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=18
https://www.franchiseindia.com/business-opportunities/education.m3?sortby=&page=19

In [48]:
h = {"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [60]:
print(len(Company))
print(len(Establishment))
print(len(Launching))
print(len(Min_Invest))
print(len(Max_Invest))
print(len(outlets))
print(len(minspace))
print(len(maxspace))
print(len(hq))

75
75
75
75
75
75
75
75
75

In [49]:
hf = pd.DataFrame(h)
hf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,Kidzee,2000,2020,10 Lac - 20 Lac,2500 - 3000,500-1000,Mumbai
1,Red SchoolHouse Pte Ltd,2004,2022,30 Lac - 50 Lac,000 - 000,Less than 10,Singapore
2,Montana International Preschool & Daycare,2014,2017,20 Lac - 30 Lac,500 - 500,Less than 10,Mumbai
3,Academy of Broadcasting,2003,2022,30 Lac - 50 Lac,1100 - 1200,Less than 10,Ropar
4,Chisel Montessori,2013,2023,20 Lac - 30 Lac,1500 - 2000,Less than 10,Chennai
...,...,...,...,...,...,...,...
71,Nava Vision,2015,2017,10 Lac - 20 Lac,500 - 1000,50-100,Bengaluru
72,Sansrev Global Edu Pvt Ltd,2001,2016,10 Lac - 20 Lac,2000 - 40000,50-100,Hyderabad
73,wonder play school,2005,2009,50 K - 2 Lac,1500sqft,65,
74,Delhi Public School Global,2017,2018,5 Lac - 10 Lac,2500 - 4000,20-50,New delhi
75,Change Lifestyle Pvt Ltd,2010,2011,10000 - 50 K,50 - 1500,Less than 10,Faridabad

In [62]:
hf.describe(include = 'all')

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
count,75,75,75,75,75,75,75,75,75
unique,75,28,21,11,11,9,28,54,43
top,Kidzee,2018,2022,10 Lac,20 Lac,Less than 10,1500,1500 - 2000,Mumbai
freq,1,8,18,18,19,38,15,7,17

In [63]:
hf.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,Kidzee,2000,2020,10 Lac,20 Lac,500-1000,2500,2500 - 3000,Mumbai
1,Montana International Preschool & Daycare,2014,2017,20 Lac,30 Lac,Less than 10,500,500 - 500,Mumbai
2,Skoodos,2022,2022,2 Lac,5 Lac,Less than 10,000,000 - 000,Gurgaon
3,Udayan Kidz,2017,2021,20 Lac,30 Lac,Less than 10,2000,2000 - 2000,New delhi
4,Pearls Montessori,2012,2021,30 Lac,50 Lac,Less than 10,3500,3500 - 3700,Bangalore

### *Fashion*

In [51]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []

for i in range(1,20):
    url = "https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
    
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())    
        
    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])    
    

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=4
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=5
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=6
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=7
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=8
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=9
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=10
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=11
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=12
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=13
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=14
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=15
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=16
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=17
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=18
https://www.franchiseindia.com/business-opportunities/fashion.m10?sortby=&page=19

In [52]:
i = {"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [66]:
print(len(Company))
print(len(Establishment))
print(len(Launching))
print(len(Min_Invest))
print(len(Max_Invest))
print(len(outlets))
print(len(minspace))
print(len(maxspace))
print(len(hq))

33
33
33
33
33
33
33
33
33

In [53]:
ii = pd.DataFrame(i)
ii

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,ROOKIES,2009,2020,50 Lac - 1 Cr,650 - 900,Less than 10,Jogeshwari east
1,Diwan Saheb,1957,2022,50 Lac - 1 Cr,3000 - 3000,Less than 10,New delhi
2,PC Jeweller Ltd.,2005,2016,5 Cr - 10 Cr,1200 - 2500,10-20,Central Delhi
3,Just In Time,2006,2021,50 Lac - 1 Cr,700 - 1500,Less than 10,Mumbai
4,Beatitude,2015,2022,30 Lac - 50 Lac,1100 - 1200,Less than 10,Pune
5,Gem Selections: Khanna Gems,1987,2019,10 Lac - 20 Lac,80 - 100,Less than 10,New Delhi
6,Aaavio.com,2021,2022,5 Lac - 10 Lac,300 - 500,Less than 10,Bangalore
7,Nandani Creation Limited (Jaipur Kurti),2012,2022,20 Lac - 30 Lac,800 - 1000,Less than 10,Jaipur
8,LABEL JAGRUTI,1990,2022,10 Lac - 20 Lac,100 - 2000,Less than 10,Ahmedabad
9,Ornazone,2022,2022,50 Lac - 1 Cr,500 - 1000,Less than 10,Kolkata
10,Specmart,2017,2020,20 Lac - 30 Lac,500 - 500,Less than 10,Haveli
11,Kala Niketan,1950,2022,50 Lac - 1 Cr,1600 - 2400,Less than 10,Mumbai
12,Bata,1950,2017,30 Lac - 50 Lac,1000 - 1200,200-500,Gurgaon
13,Paislei,2008,2008,20 Lac - 30 Lac,500 - 800,20-50,New delhi
14,PRATHAM SILVER,1985,2022,1 Cr - 2 Cr,400 - 500,Less than 10,Himatnagar
15,Jagran Micro Motors Ltd. (Balenzia),2019,2022,10 Lac - 20 Lac,100 - 150,Less than 10,Lajpat nagar
16,Liberty Shoes Ltd,1954,1995,20 Lac - 30 Lac,500 - 1000,100-200,Gurgaon
17,Biba,1988,2019,2 Cr - 5 Cr,800 - 1000,10-20,Gurugram
18,Being Human,2012,2013,50 Lac - 1 Cr,1000 Sq. ft. to 1800 Sq. ft.,6,Mumbai
19,Fabindia Limited,1960,2014,50 Lac - 1 Cr,1000 - 2500,200-500,New delhi
20,READY FOR YOU TRADERS PRIVATE LIMITED,2010,2014,20 Lac - 30 Lac,450 - 1500,No,New Delhi
21,Khadim India Ltd.,1993,1996,20 Lac - 30 Lac,500 to 1000 sq. ft. carpet area with 20 ft. fr...,486,Kolkata
22,Lenskart.com,2010,2013,20 Lac - 30 Lac,300 - 500,200-500,Faridabad
23,LINEN HOUSE,2019,2019,20 Lac - 50 Lac,600 - 1000,10-20,Hyderabad
24,ClearDekho Eyewear Pvt Ltd,2016,2016,10 Lac - 20 Lac,200 - 300,50-100,Ghaziabad
25,Abhiruchi Costume Kart,2003,2017,10000 - 50 K,400 - 2000 Sq.ft,Less than 10,South Delhi
26,CLASSIC POLO,2001,2008,10 Lac - 20 Lac,400-600 Sq. Ft.,66,BANGALORE
27,COCO LENI,2017,2021,10 Lac - 20 Lac,100 - 2000,Less than 10,Tiswadi
28,Caratlane Trading Pvt Ltd.,2008,2008,10000 - 50 K,None,Less than 10,Chennai
29,Red Tape,2007,2007,10 Lac - 20 Lac,-N/A-,36,
30,Bombay Dyeing,1950,1979,10 Lac - 20 Lac,300 - 500,100-200,Mumbai
31,Baggit India Pvt Ltd,1989,2007,10 Lac - 20 Lac,100 - 250,50-100,Mumbai
32,Creez,2018,2020,30 Lac - 50 Lac,600 - 600,Less than 10,Faridabad

In [68]:
ii.describe(include = 'all')

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
count,33,33,33,33,33,33,33,33,33
unique,33,26,13,9,9,11,19,28,23
top,Gem Selections: Khanna Gems,1950,2022,10 Lac,20 Lac,Less than 10,500,300 - 500,Mumbai
freq,1,3,9,9,9,17,5,3,5

In [69]:
ii.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,Gem Selections: Khanna Gems,1987,2019,10 Lac,20 Lac,Less than 10,80,80 - 100,New Delhi
1,PRATHAM SILVER,1985,2022,1 Cr,2 Cr,Less than 10,400,400 - 500,Himatnagar
2,Just In Time,2006,2021,50 Lac,1 Cr,Less than 10,700,700 - 1500,Mumbai
3,Diwan Saheb,1957,2022,50 Lac,1 Cr,Less than 10,3000,3000 - 3000,New delhi
4,Beatitude,2015,2022,30 Lac,50 Lac,Less than 10,1100,1100 - 1200,Pune

### *Retail*

In [41]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []


for i in range(1,20):
    url = "https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
           
   
    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])

    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip()) 
    
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())    
        

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=4
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=5
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=6
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=7
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=8
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=9
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=10
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=11
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=12
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=13
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=14
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=15
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=16
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=17
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=18
https://www.franchiseindia.com/business-opportunities/retail.m9?sortby=&page=19

In [42]:
j ={"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [44]:
print(len(Company))
print(len(Establishment))
print(len(Launching))
print(len(Investment))
print(len(space))

#print(len(Min_Invest))
#print(len(Max_Invest))
print(len(outlets))
#print(len(minspace))
#print(len(maxspace))
print(len(hq))

73
73
73
73
73
73
73

In [45]:
jf = pd.DataFrame(j)
jf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,Kuber Shoppe,2016,2020,30 Lac - 50 Lac,1000 - 1500,Less than 10,New delhi
1,Berrylush,2018,2022,20 Lac - 30 Lac,1000 - 1100,Less than 10,Bishrakh
2,RockingDeals,2002,2007,1 Cr - 2 Cr,5000 - 5000,50-100,Faridabad
3,Snackstar,2020,2022,10 Lac - 20 Lac,100 - 200,Less than 10,New delhi
4,Innovative Design Associates,2022,2022,2 Lac - 5 Lac,00 - 000,Less than 10,Faridabad
...,...,...,...,...,...,...,...
68,MW MART,2021,2022,50 K - 2 Lac,700 - 2000,Less than 10,Kalyan
69,Blinkit,2016,2019,20 Lac - 30 Lac,1000 - 2500,10-20,Gurugram
70,Siyaram Silk Mills Ltd,1978,2006,20 Lac - 30 Lac,800 - 1000,200-500,Mumbai City
71,MIKHADI VILLAGE ARTISANS,2012,2014,10000 - 20 Lac,500 - 5000,Less than 10,BADLAPUR
72,Door2Door - Dravidian eRetail Services Private...,2014,2017,5 Lac - 10 Lac,1000,Less than 10,Coimbatore

In [73]:
jf.describe(include = 'all')

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
count,73,73,73,73,73,73,73,73,73
unique,73,32,18,12,11,7,27,56,33
top,Sarvalaya Divine Private Limited,2020,2022,20 Lac,30 Lac,Less than 10,1000,1500 - 3000,Faridabad
freq,1,8,29,17,17,45,11,3,9

In [74]:
jf.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,Sarvalaya Divine Private Limited,1977,2022,30 Lac,50 Lac,Less than 10,500,500 - 2500,Visakhapatnam
1,Masonite Doors,2009,2020,10000,50 K,Less than 10,300,300 - 600,New delhi
2,Idecorwala,2010,2022,10 Lac,20 Lac,Less than 10,-N/A-,-N/A-,Chennai
3,Sports Station,2005,2011,50 Lac,1 Cr,50-100,1500,1500 - 2000,Delhi
4,AKI Fresh Mart,2000,2022,30 Lac,50 Lac,50-100,600,600 - 3000,Faridabad

In [75]:
jf

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Maximum Space (in sft),Headquarter
0,Sarvalaya Divine Private Limited,1977,2022,30 Lac,50 Lac,Less than 10,500,500 - 2500,Visakhapatnam
1,Masonite Doors,2009,2020,10000,50 K,Less than 10,300,300 - 600,New delhi
2,Idecorwala,2010,2022,10 Lac,20 Lac,Less than 10,-N/A-,-N/A-,Chennai
3,Sports Station,2005,2011,50 Lac,1 Cr,50-100,1500,1500 - 2000,Delhi
4,AKI Fresh Mart,2000,2022,30 Lac,50 Lac,50-100,600,600 - 3000,Faridabad
...,...,...,...,...,...,...,...,...,...
68,Manak Waste Management Pvt Ltd (Cashify),2015,2020,10 Lac,20 Lac,10-20,150,150 - 350,Gurugram
69,XIMIVOGUE TRADING LLP,2018,2018,20 Lac,30 Lac,50-100,250,250 - 500,New delhi
70,Blinkit,2016,2019,20 Lac,30 Lac,10-20,1000,1000 - 2500,Gurugram
71,24 Seven,2000,2008,50 Lac,1 Cr,100-200,1000,1000 - 1200,Delhi
72,Door2Door - Dravidian eRetail Services Private...,2014,2017,5 Lac,10 Lac,Less than 10,1000,1000,Coimbatore

### *Hotel, Travel and Tourism*

In [33]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []


for i in range(1,5):
    url = "https://www.franchiseindia.com/business-opportunities/hotels-and-resorts.m263?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
           
  
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())    
        
    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/hotels-and-resorts.m263?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/hotels-and-resorts.m263?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/hotels-and-resorts.m263?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/hotels-and-resorts.m263?sortby=&page=4

In [34]:
k = {"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [35]:
kf = pd.DataFrame(k)
kf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,Neem Holidays,2001,2022,5 Lac - 10 Lac,250 - 250,Less than 10,Goregaon east
1,Ajay ModiTravels Pvt. Ltd,1997,2022,5 Lac - 10 Lac,250 - 300,Less than 10,Ahmedabad

### *Home Based Business*

In [36]:
Company = []
Establishment = []
Launching = []
Investment= []
outlets = []
space = []
hq = []


for i in range(1,5):
    url = "https://www.franchiseindia.com/business-opportunities/home-based-business.m7?sortby=&page="+str(i)
    print(url)
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    data = soup.find_all("div" , class_ = "commanmbsmobile")
    location = soup.find_all('div', class_ = "catdright pad20")
    companyname = soup.find_all("div", class_ = "catlist")
    
    for i in data:
        a = i.text
        Establishment.append(a.replace("\n","").split()[2])
        
    for i in companyname:
        a = i.text
        b= a.strip()
        Company.append(b.replace("\n",""))
           
   
    for i in data:
        a = i.text
        Launching.append(a.split("Date")[1].split()[0])
        
    for i in data:
        a = i.text
        outlets.append(a.split('Outlets')[1].strip())    

    for i in data:
        a = i.text
        b = space.append(a.split('required')[1].split('\n')[1].strip())

    for i in data:
        a = i.text
        b = Investment.append(a.split("INR")[1].split('\n')[0])

    for i in location:
        a = i.text
        hq.append(a.split('Headquarter')[1].split('\n')[1].strip())

https://www.franchiseindia.com/business-opportunities/home-based-business.m7?sortby=&page=1
https://www.franchiseindia.com/business-opportunities/home-based-business.m7?sortby=&page=2
https://www.franchiseindia.com/business-opportunities/home-based-business.m7?sortby=&page=3
https://www.franchiseindia.com/business-opportunities/home-based-business.m7?sortby=&page=4

In [37]:
l = {"Company": Company,
    "Establishing Year": Establishment,
     "Launching Year": Launching,
     "Investment" : Investment,
     "Space Required" : space,
    "Outlets": outlets,
    "Headquarter" : hq}

In [38]:
lf = pd.DataFrame(l)
lf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,House of Cure,2020,2022,50 Lac - 1 Cr,1000 - 2000,Less than 10,Mumbai
1,Rentomojo,2014,2022,20 Lac - 30 Lac,00 - 000,100-200,Bangalore
2,Collins,1986,2022,50 Lac - 1 Cr,2000 - 3000,Less than 10,Mumbai
3,South Indian Junction,2017,2020,50 K - 2 Lac,400 - 500,Less than 10,Pondicherry
4,FBI industries,1999,2021,20 Lac - 30 Lac,1000 - 3000,Less than 10,Deharaudn

In [58]:
sf = pd.concat((lf,kf,jf,hf,ii,gf),axis = 0)
sf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,House of Cure,2020,2022,50 Lac - 1 Cr,1000 - 2000,Less than 10,Mumbai
1,Rentomojo,2014,2022,20 Lac - 30 Lac,00 - 000,100-200,Bangalore
2,Collins,1986,2022,50 Lac - 1 Cr,2000 - 3000,Less than 10,Mumbai
3,South Indian Junction,2017,2020,50 K - 2 Lac,400 - 500,Less than 10,Pondicherry
4,FBI industries,1999,2021,20 Lac - 30 Lac,1000 - 3000,Less than 10,Deharaudn
...,...,...,...,...,...,...,...
9,Eos Cinemas Pvt. Ltd,2013,2015,50 Lac - 1 Cr,-N/A-,Less than 10,Bastar
10,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lac - 1 Cr,2000 - 4000,Less than 10,Deharaudn
11,ResQRoom,2016,2018,10 Lac - 20 Lac,700 - 900,10-20,Haveli
12,House of Fitness pvt ltd,2012,2012,2 Cr - 5 Cr,3500 - 5000,50-100,Delhi
13,All Things love,2016,2020,10 Lac - 20 Lac,500 - 5000,Less than 10,Gurgaon

In [83]:
sf.drop(columns = 'Maximum Space (in sft)', inplace = True)
sf

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,Rentomojo,2014,2022,20 Lac,30 Lac,100-200,00,Bangalore
1,House of Cure,2020,2022,50 Lac,1 Cr,Less than 10,1000,Mumbai
2,Collins,1986,2022,50 Lac,1 Cr,Less than 10,2000,Mumbai
3,South Indian Junction,2017,2020,50 K,2 Lac,Less than 10,400,Pondicherry
4,FBI industries,1999,2021,20 Lac,30 Lac,Less than 10,1000,Deharaudn
...,...,...,...,...,...,...,...,...
9,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lac,1 Cr,Less than 10,2000,Deharaudn
10,Eos Cinemas Pvt. Ltd,2013,2015,50 Lac,1 Cr,Less than 10,-N/A-,Bastar
11,ResQRoom,2016,2018,10 Lac,20 Lac,10-20,700,Haveli
12,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
13,All Things love,2016,2020,10 Lac,20 Lac,Less than 10,500,Gurgaon

In [84]:
sf.reset_index(inplace = True)
sf.drop('index', axis = 1, inplace = True)
sf

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,Rentomojo,2014,2022,20 Lac,30 Lac,100-200,00,Bangalore
1,House of Cure,2020,2022,50 Lac,1 Cr,Less than 10,1000,Mumbai
2,Collins,1986,2022,50 Lac,1 Cr,Less than 10,2000,Mumbai
3,South Indian Junction,2017,2020,50 K,2 Lac,Less than 10,400,Pondicherry
4,FBI industries,1999,2021,20 Lac,30 Lac,Less than 10,1000,Deharaudn
...,...,...,...,...,...,...,...,...
197,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lac,1 Cr,Less than 10,2000,Deharaudn
198,Eos Cinemas Pvt. Ltd,2013,2015,50 Lac,1 Cr,Less than 10,-N/A-,Bastar
199,ResQRoom,2016,2018,10 Lac,20 Lac,10-20,700,Haveli
200,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
201,All Things love,2016,2020,10 Lac,20 Lac,Less than 10,500,Gurgaon

In [85]:
sf.head()

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,Rentomojo,2014,2022,20 Lac,30 Lac,100-200,00,Bangalore
1,House of Cure,2020,2022,50 Lac,1 Cr,Less than 10,1000,Mumbai
2,Collins,1986,2022,50 Lac,1 Cr,Less than 10,2000,Mumbai
3,South Indian Junction,2017,2020,50 K,2 Lac,Less than 10,400,Pondicherry
4,FBI industries,1999,2021,20 Lac,30 Lac,Less than 10,1000,Deharaudn

In [68]:
tf = pd.concat((bf,ef,ff),axis = 0)
tf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,What a Sandwich,2013,2018,2 Lac - 5 Lac,200 - 1300,100-200,Pune
1,Go69 Pizza,2015,2016,50 K - 2 Lac,200 - 250,50-100,Lucknow
2,THE GRANIOS,2013,2017,5 Lac - 10 Lac,100 - 800,10-20,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac - 20 Lac,100 - 150,100-200,New delhi
4,Brewbakes,2014,2015,30 Lac - 50 Lac,500 - 2000,100-200,Delhi
...,...,...,...,...,...,...,...
86,Medlife Pharma healthcare Pvt Ltd,2014,2017,50 K - 2 Lac,120 - 200,Less than 10,Chalisgaon
87,Framekart.com,1995,2019,10000 - 50 K,200 - 3000,Less than 10,Patna
88,"Max Lab, A Division of Max Healthcare Institut...",2016,2016,50 K - 2 Lac,150 - 200,100-200,Gurgaon
89,NephroPlus,2009,2020,10 Lac - 20 Lac,1330 - 1330,Less than 10,Faridabad
90,Ayouthveda,2020,2021,30 Lac - 50 Lac,300 - 400,Less than 10,Delhi

In [69]:
tf.reset_index(inplace = True)
tf.drop('index', axis = 1, inplace = True)
tf

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,What a Sandwich,2013,2018,2 Lac - 5 Lac,200 - 1300,100-200,Pune
1,Go69 Pizza,2015,2016,50 K - 2 Lac,200 - 250,50-100,Lucknow
2,THE GRANIOS,2013,2017,5 Lac - 10 Lac,100 - 800,10-20,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac - 20 Lac,100 - 150,100-200,New delhi
4,Brewbakes,2014,2015,30 Lac - 50 Lac,500 - 2000,100-200,Delhi
...,...,...,...,...,...,...,...
255,Medlife Pharma healthcare Pvt Ltd,2014,2017,50 K - 2 Lac,120 - 200,Less than 10,Chalisgaon
256,Framekart.com,1995,2019,10000 - 50 K,200 - 3000,Less than 10,Patna
257,"Max Lab, A Division of Max Healthcare Institut...",2016,2016,50 K - 2 Lac,150 - 200,100-200,Gurgaon
258,NephroPlus,2009,2020,10 Lac - 20 Lac,1330 - 1330,Less than 10,Faridabad
259,Ayouthveda,2020,2021,30 Lac - 50 Lac,300 - 400,Less than 10,Delhi

In [98]:
tf.drop('Maximum Space (in sft)', axis = 1, inplace = True)
tf

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lac,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lac,10 Lac,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lac,5 Lac,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac,20 Lac,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lac,30 Lac,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
253,"Max Lab, A Division of Max Healthcare Institut...",2016,2016,50 K,2 Lac,100-200,150,Gurgaon
254,The Kerala Ayurveda Centre,2002,2014,10000,50 K,0,commercial,Jalandhar
255,Framekart.com,1995,2019,10000,50 K,Less than 10,200,Patna
256,NephroPlus,2009,2020,10 Lac,20 Lac,Less than 10,1330,Faridabad
257,Ayouthveda,2020,2021,30 Lac,50 Lac,Less than 10,300,Delhi

In [70]:
df = pd.concat((tf,sf), axis = 0)
df

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,What a Sandwich,2013,2018,2 Lac - 5 Lac,200 - 1300,100-200,Pune
1,Go69 Pizza,2015,2016,50 K - 2 Lac,200 - 250,50-100,Lucknow
2,THE GRANIOS,2013,2017,5 Lac - 10 Lac,100 - 800,10-20,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac - 20 Lac,100 - 150,100-200,New delhi
4,Brewbakes,2014,2015,30 Lac - 50 Lac,500 - 2000,100-200,Delhi
...,...,...,...,...,...,...,...
9,Eos Cinemas Pvt. Ltd,2013,2015,50 Lac - 1 Cr,-N/A-,Less than 10,Bastar
10,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lac - 1 Cr,2000 - 4000,Less than 10,Deharaudn
11,ResQRoom,2016,2018,10 Lac - 20 Lac,700 - 900,10-20,Haveli
12,House of Fitness pvt ltd,2012,2012,2 Cr - 5 Cr,3500 - 5000,50-100,Delhi
13,All Things love,2016,2020,10 Lac - 20 Lac,500 - 5000,Less than 10,Gurgaon

In [71]:
df.reset_index(inplace = True)
df.drop('index', axis = 1, inplace = True)
df

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,What a Sandwich,2013,2018,2 Lac - 5 Lac,200 - 1300,100-200,Pune
1,Go69 Pizza,2015,2016,50 K - 2 Lac,200 - 250,50-100,Lucknow
2,THE GRANIOS,2013,2017,5 Lac - 10 Lac,100 - 800,10-20,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac - 20 Lac,100 - 150,100-200,New delhi
4,Brewbakes,2014,2015,30 Lac - 50 Lac,500 - 2000,100-200,Delhi
...,...,...,...,...,...,...,...
458,Eos Cinemas Pvt. Ltd,2013,2015,50 Lac - 1 Cr,-N/A-,Less than 10,Bastar
459,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lac - 1 Cr,2000 - 4000,Less than 10,Deharaudn
460,ResQRoom,2016,2018,10 Lac - 20 Lac,700 - 900,10-20,Haveli
461,House of Fitness pvt ltd,2012,2012,2 Cr - 5 Cr,3500 - 5000,50-100,Delhi
462,All Things love,2016,2020,10 Lac - 20 Lac,500 - 5000,Less than 10,Gurgaon

In [72]:
df

,Company,Establishing Year,Launching Year,Investment,Space Required,Outlets,Headquarter
0,What a Sandwich,2013,2018,2 Lac - 5 Lac,200 - 1300,100-200,Pune
1,Go69 Pizza,2015,2016,50 K - 2 Lac,200 - 250,50-100,Lucknow
2,THE GRANIOS,2013,2017,5 Lac - 10 Lac,100 - 800,10-20,khammam
3,CHICAGO PIZZA,2000,2007,10 Lac - 20 Lac,100 - 150,100-200,New delhi
4,Brewbakes,2014,2015,30 Lac - 50 Lac,500 - 2000,100-200,Delhi
...,...,...,...,...,...,...,...
458,Eos Cinemas Pvt. Ltd,2013,2015,50 Lac - 1 Cr,-N/A-,Less than 10,Bastar
459,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lac - 1 Cr,2000 - 4000,Less than 10,Deharaudn
460,ResQRoom,2016,2018,10 Lac - 20 Lac,700 - 900,10-20,Haveli
461,House of Fitness pvt ltd,2012,2012,2 Cr - 5 Cr,3500 - 5000,50-100,Delhi
462,All Things love,2016,2020,10 Lac - 20 Lac,500 - 5000,Less than 10,Gurgaon

# CLEANING

In [105]:
df["Minimum Investment"] = df["Minimum Investment"].str.replace('Lac','Lakh')
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,-N/A-,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

In [144]:
df["Maximum Investment"] = df["Maximum Investment"].str.replace('Lac','Lakh')
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,2000,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

In [107]:
df["Minimum Space (in sft)"].value_counts()

200           40
500           38
300           34
1500          33
100           32
1000          32
150           24
-N/A-         23
800           21
250           14
400           14
600           14
1200          11
2000          11
3000          10
700           10
00             9
5000           8
2500           8
000            7
50             7
350            5
900            5
1100           4
1600           3
4000           3
10             3
3500           3
80             2
10000          2
70             2
6000           2
1300           2
650            2
60             2
450            1
1500sqft       1
150-300        1
850            1
400-600        1
65000          1
65340          1
8000           1
None           1
01             1
1800           1
1330           1
commercial     1
120            1
550            1
1700           1
12000          1
1350           1
1000-1500      1
750            1
Name: Minimum Space (in sft), dtype: int64

In [ ]:
df2['price']=df2['price'].astype("int")

In [143]:
df["Minimum Space (in sft)"] = df["Minimum Space (in sft)"].replace({'-N/A-': np.NaN})
#df["Minimum Space (in sft)"].fillna(method = 'bfill')
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,2000,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

In [151]:
df['Minimum Space (in sft)'].fillna(method ='bfill', inplace = True)
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,2000,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

In [180]:
df["Minimum Space (in sft)"] = df["Minimum Space (in sft)"].replace({'400-600': np.NaN,'1000-1500': np.NaN,'150-300': np.NaN,'commercial': np.NaN})
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,2000,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

In [181]:
df['Minimum Space (in sft)'].fillna(df['Minimum Space (in sft)'].mode()[0], inplace = True)
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,2000,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

In [182]:
df['Minimum Space (in sft)'].value_counts()

200      57
500      40
300      38
1500     37
100      36
1000     34
150      24
800      24
250      16
400      15
2000     14
600      14
700      12
1200     12
3000     10
2500      9
5000      8
900       7
1100      5
350       5
1600      4
3500      3
4000      3
65000     3
60        2
120       2
6000      2
550       2
10000     2
1300      2
80        2
650       2
70        2
12000     1
1800      1
1330      1
01        1
1350      1
8000      1
65340     1
1700      1
850       1
450       1
None      1
750       1
Name: Minimum Space (in sft), dtype: int64

In [210]:
df.isnull().sum()

Company                   0
Establishing Year         0
Launching Year            0
Minimum Investment        0
Maximum Investment        0
Outlets                   0
Minimum Space (in sft)    0
Headquarter               0
dtype: int64

In [186]:
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,2000,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

'C:\\Users\\Mukesh Anchuri'

In [207]:
df.to_csv("Franchise India.csv")

In [208]:
df

,Company,Establishing Year,Launching Year,Minimum Investment,Maximum Investment,Outlets,Minimum Space (in sft),Headquarter
0,What a Sandwich,2013,2018,50 K,2 Lakh,100-200,200,Pune
1,Go69 Pizza,2015,2016,5 Lakh,10 Lakh,50-100,100,Lucknow
2,THE GRANIOS,2013,2017,2 Lakh,5 Lakh,10-20,200,khammam
3,CHICAGO PIZZA,2000,2007,10 Lakh,20 Lakh,100-200,100,New delhi
4,U.S. Pizza,1998,2002,20 Lakh,30 Lakh,50-100,250,Bangalore Urban District
...,...,...,...,...,...,...,...,...
455,SGL MINIPLEX PRIVATE LIMITED,2020,2020,50 Lakh,1 Cr,Less than 10,2000,Deharaudn
456,Eos Cinemas Pvt. Ltd,2013,2015,50 Lakh,1 Cr,Less than 10,2000,Bastar
457,ResQRoom,2016,2018,10 Lakh,20 Lakh,10-20,700,Haveli
458,House of Fitness pvt ltd,2012,2012,2 Cr,5 Cr,50-100,3500,Delhi
459,All Things love,2016,2020,10 Lakh,20 Lakh,Less than 10,500,Gurgaon

In [7]:


for i in data2:
    a = i.text
    b = Investment.append(a.split("INR")[1].split('\n')[0])
    
for i in data2:
    a = i.text
    b = space.append(a.split('required')[1].split('\n')[1].strip())

['100 - 800',
 '200 - 250',
 '200 - 1300',
 '100 - 150',
 '250 - 1000',
 '500 - 2000',
 '100 - 5000',
 '100 - 1000',
 '100 - 1000',
 '800 - 1000',
 '100 - 500',
 '250 - 400',
 '100 - 300',
 '00 - 000',
 '250 - 2000',
 '1200 - 1500',
 '150 - 300',
 '-N/A-',
 '300 - 2000',
 '100 - 400',
 '200 - 400']

In [8]:
Investment = []
for i in data2:
    a = i.text
    b = Investment.append(a.split("INR")[1].split('\n')[0])
Investment

['  5 Lac  - 10 Lac ',
 '  50 K  - 2 Lac ',
 '  2 Lac  - 5 Lac ',
 '  10 Lac  - 20 Lac ',
 '  20 Lac  - 30 Lac ',
 '  30 Lac  - 50 Lac ',
 '  5 Lac  - 10 Lac ',
 '  10 Lac  - 20 Lac ',
 '  10 Lac  - 2 Cr ',
 '  50 Lac  - 1 Cr ',
 '  5 Lac  - 10 Lac ',
 '  10 Lac  - 20 Lac ',
 '  10 Lac  - 20 Lac ',
 '  10 Lac  - 20 Lac ',
 '  50 Lac  - 1 Cr ',
 '  1 Cr  - 2 Cr ',
 '  10 Lac  - 20 Lac ',
 '  30 Lac  - 50 Lac ',
 '  10 Lac  - 20 Lac ',
 '  2 Lac  - 5 Lac ',
 '  10 Lac  - 20 Lac ']